# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Enable smart quotes/dashes
redcarpet:
  extensions: ['smart']

# Setup
title:            Bitbanter 
tagline:          The musings of a renersatz man
description:      The musings of a renersatz man
url:              "http://bitbanter.com"

author:
  name:           "Josh Cincinnati"
  twit:           "ACityInOhio"
  twiturl:        "https://twitter.com/acityinohio"
  gurl:           "https://plus.google.com/115508762054502274726?rel=author"
  fburl:          "https://www.facebook.com/josh.cincinnati"
  btc:            "https://coinbase.com/cin"

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ACityInOhio/ACityInOhio.github.io 

# List of pages to include in header
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
